In [1]:
print("halo alpan")

halo alpan


In [2]:
#kondisional if
nurul = 12000
alpan = 10000
nesa = 4000
tita = 2500
danul = 2000
print(nurul)
print(alpan)
print(tita)
print(nesa)
print(danul)

12000
10000
2500
4000
2000


In [3]:
#pernyataan if-else
alprog = 2106009
fislis = 2106047
if alprog > fislis:
    print("alprog lebih besar dari fislis")
else:
    print("fislis lebih besar dari alprog")

fislis lebih besar dari alprog


In [6]:
print("besar") if alprog > fislis else print("kecil")

kecil


In [7]:
#nested bersarang
umur_orang = 19
if umur_orang > 7:
    print("Bisa naik")
    if umur_orang > 18:
        print("nggak perlu diawasi")
    else:
        print("dit tolongin dit")
else:
    print("nggak boleh")


Bisa naik
nggak perlu diawasi


In [8]:
#if-elif-else
#program kualifikasi kualitas kos tembalang sesuai harga 
uang = 1500000

if uang >= 20000000:
    print("kost rasa apartemen")
elif uang >= 1200000 and uang <= 20000000:
    print("kost ber AC dan kamar mandi dalam")
elif uang >= 800000 and uang <= 1200000:
    print("kost ber AC dan kamar mandi luar")
elif uang >= 500000 and uang <= 800000:
    print("kost non AC kamar mandi luar")
else:
    print("dit tolongin dit")

kost ber AC dan kamar mandi dalam


In [9]:
#pass
harga_steak = 60000
if harga_steak > 100000:
    pass
else:
    print("bukan steak mewah")

bukan steak mewah


In [13]:
#looping on array/list
list_siswa = ["bella","anna","elsa","ariel"]
for siswa in list_siswa:
    print(siswa)

bella
anna
elsa
ariel


In [ ]:
#break dalam for
jumat_berkah_enak = ["alfalah","maskam","FEB"]
for makanan in jumat_berkah_enak:
    print()

In [16]:
#range()
for i in range(6):
    print("persdif gampang banget")

persdif gampang banget
persdif gampang banget
persdif gampang banget
persdif gampang banget
persdif gampang banget
persdif gampang banget


In [17]:
#continue dalam for
for i in range (5):
    if i == 2:
        continue
    print (i)

0
1
3
4


In [18]:
#range() 3 parameter
start = 3
stop = 9
step = 2
for y in range (start, stop, step):
    print(y)

3
5
7


In [ ]:
#break and continue
#break --> stop loop
#continue --> next the loop
i =1 
while i <8:
    print(i)
    i += 1
    if i == 6:
        break

In [19]:
#nested looping
sifat = ["hitam","panjang","besar"]
karakter = ["kekar","lemas","kokoh"]
for p in sifat :
    for i in karakter:
        print(p,i)

hitam kekar
hitam lemas
hitam kokoh
panjang kekar
panjang lemas
panjang kokoh
besar kekar
besar lemas
besar kokoh


In [20]:
#pass di looping
for a in range (1,4, 5):
    pass

In [ ]:
#membuat matriks menggunakan for dan list
matriks_NIM = []
for i in range(0,5):
    baris_matriks = []
    for j in range (0,3):
        isi_NIM = int("Masukan 3 digit terakkhir NIM anda: ")

In [21]:
import numpy

In [ ]:
matriks_percobaan = numpy.array([[1,2],[3,4]])
print(matriks_percobaan)

[[1 2]
 [3 4]]


In [24]:
import numpy as np
matriks_percobaan = np.array([[1,2],[3,4]])
print(matriks_percobaan)

[[1 2]
 [3 4]]


In [ ]:
#aarray 3 dimensi indexing
arra2D = wkwk.array([[1,2],[3,4]])
print(arra2D)
print(arra2D[0])
print


In [25]:
#array pada numpy
#array 0 dimensi
import numpy as wkwk
D0 = wkwk.array(5)
print(D0)

5


In [ ]:
#array 3 dimensi
D3 = wkwk.array([[1,2],[3,4]])

In [ ]:
#operasi aritmatika pada array 3 dimensi
print

In [26]:
#tipe data pada numpy
ara_ara = wkwk.array()

TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
#buat array dengan tipe data tertentu
ara ara = wkwk.array?

In [ ]:
#konversi jenis data pada array
import numpy as np
arr_lama = np.array([1.1,1.2,1.3])


In [27]:
#menyalin array
#copy
nomer_tugel = np.array([1,2,3])
print(nomer_tugel)
p = nomer_tugel.copy()
nomer_tugel[3]=45
print(nomer_tugel)
print(p)

[1 2 3]


IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
#view
nomer_tugel = np.array([1,2,3])
print(nomer_tugel)
q = nomer_tokek.view()
