In [6]:
a = 33
b = 200

if b > a:
    print(' b lebih besar dari a')

 b lebih besar dari a


In [53]:
# indentasi
if b > a:
print(' b lebih besar dari a')

IndentationError: expected an indented block after 'if' statement on line 2 (2227168228.py, line 3)

In [10]:
# indentasi
if b > a:
    print(' b lebih besar dari a')
elif a == b:
    print(' a sama dengan b')

 b lebih besar dari a


In [ ]:
# else
if b < a:
    print(' a lebih besar dari b')

else:
    print('b lebih besar dari a')

b lebih besar dari a


In [2]:
#  bentuk if yang pendek
a = 30
b = 20

if a > b: print(' a lebih besar dari b')

 a lebih besar dari b


In [25]:
a = 330
b = 330

print ("a") if a == b else print("b") if b == a else print("B")

print("a" if a == b else "b" if b == a else "B")

a
a


In [5]:
# Penggunaan and
a = 600
b = 400
c = 500

if a > b and c < a:
    print("kedua kondisi benar")    

kedua kondisi benar


In [6]:
# Nested if
x = 33

if x > 19:
    print("x di atas 19")

    if x > 30 :
        print("dan juga lebih dari 30")

    else:
        print("tetapi di bawah 30")

x di atas 19
dan juga lebih dari 30


In [27]:
# pass 
nilai1 = 22
nilai2 = 300

if b > a:
    pass
else:
    print("ok")

ok


In [28]:
# perulangan
i = 1

while i <= 6:
    print(i)
    i += 1      

1
2
3
4
5
6


In [31]:
# pernyataan break
i = 1

while i >= -10:
    print(i)
    if i == -2:
        break

    i -= 1
    


1
0
-1
-2


In [33]:
# pernyataan break
i = 1

while i >= -10:
    i -= 1
    if i == -2:
        continue

    print(i)
    


0
-1
-3
-4
-5
-6
-7
-8
-9
-10
-11


In [ ]:
# else

i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i sudah berhenti 6")


1
2
3
4
5
i sudah berhenti 6


In [38]:
# looping denan for

buah = ["pisang", "anggur", "apel"]
for x in buah:
    print(x)

pisang
anggur
apel


In [39]:
string = "kata"

for x in string:
    print(x)

k
a
t
a


In [ ]:
# continue
kata = "kata - kata"

for huruf in kata:
    if huruf == "-":
        continue
    print(huruf)


k
a
t
a
 
 
k
a
t
a


In [42]:
# fungsi range()

for i in range(5):
    print("angka ke -", str(i))

angka ke - 0
angka ke - 1
angka ke - 2
angka ke - 3
angka ke - 4


In [44]:
for i in range(2, 6, 2):
    print("angka ke -", str(i))
else :
    print("angka sudah bernilai enam")

angka ke - 2
angka ke - 4
angka sudah bernilai enam


In [45]:
# perulangan bersarang
tipe_ukuran = ["besar", "sedang", "kecil"]   
kumpulan_buah = ["durian", "mangga"]

for buah in kumpulan_buah:
    for ukuran_buah in tipe_ukuran:
        print(buah, ukuran_buah)

durian besar
durian sedang
durian kecil
mangga besar
mangga sedang
mangga kecil


In [50]:
# range bersarang
for i in range(1,4):
    for j in range(1,3):
        print(str(i) + '.' + str(j))

1.1
1.2
2.1
2.2
3.1
3.2


In [ ]:
# pernyataan pass
for x in [2, 3, 4]:
    pass # tidak ada keluaran

Modul 5

In [ ]:
import numpy as np

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7 ,8, 9, 10])
print(arr)

print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array(50) #array 0 dimensi
arr1 = np.array([1,2,3,4,5]) # arrar 1 dimensi
arr2 = np.array([[1,2,3],[4,5,6]]) # arrar 2 dimensi    
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # arrar 3 dimensi

print(arr)
print(arr1)
print(arr2)
print(arr3) 

50
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [62]:
arr = np.array(50) #arrar 0 dimensi
arr1 = np.array([1,2,3,4,5]) # arrar 1 dimensi
arr2 = np.array([[1,2,3],[4,5,6]]) # arrar 2 dimensi    
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # arrar 3 dimensi


print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim) 

0
1
2
3


In [64]:
#  indexing 
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(numbers[0]) # 1
print(numbers[1]) # 2
print(numbers[2]) # 3

print(numbers[0] + numbers[3]) # 4

1
2
3
5


In [65]:
arr2 = np.array([[1,2,3],[4,5,6]]) # arrar 2 dimensi

print(arr2[0, -1]) 

3


In [66]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # arrar 3 dimensi

print(arr3[0, 1, 2]) # 6   

6


In [3]:
# numpy array slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1:5]) 

print(arr[:5])
print(arr[0:5])

print(arr[-3:-1])

print(arr)
print(arr[::2]) # ambil setiap 2 angka

# cetak dngan tahap
print(arr)
print (arr[0:5:2])

[2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]


In [77]:
arr2 = np.array([[1,2,3],[4,5,6]]) # arrar 2 dimensi

print(arr2[0, :3]) # 1

print(arr2[:, :2]) 


[1 2 3]
[[1 2]
 [4 5]]


In [78]:
# Tipe Data
arr = np.array([1, 2, 3]) # arrar 1 dimensi

original = arr.dtype
print(original) # int64

int64


In [80]:
elektronik = np.array(["Komuputer", "laptop"]) # arrar 1 dimensi
print(elektronik.dtype) # float64

<U9


In [81]:
# membuat array dengan tipe data tertentu
arr = np.array([1, 2, 3], dtype = 'i4') # arrar 1 dimensi
print(arr)
print(arr.dtype) # int32    

[1 2 3]
int32


In [83]:
# membuat array dengan tipe data tertentu
arr = np.array([1, 2, 3], dtype = 'S') # arrar 1 dimensi
print(arr)
print(arr.dtype) # int32    

[b'1' b'2' b'3']
|S1


In [85]:
arr = np.array([[1,2,3],[4,5,6]]) # arrar 2 dimensi
arr1 = np.astype(arr, 'S') # ubah tipe data menjadi string

print(arr)
print(arr.dtype) 

print(arr1)
print(arr1.dtype) 

[[1 2 3]
 [4 5 6]]
int64
[[b'1' b'2' b'3']
 [b'4' b'5' b'6']]
|S21


In [88]:
arr = np.array([[1.1,2.2,3.3],[4.3,5.1,6.2]]) # arrar 2 dimensi
arr1 = np.astype(arr, 'bool') # ubah tipe data menjadi string

print(arr)
print(arr.dtype) 

print(arr1)
print(arr1.dtype) 

[[1.1 2.2 3.3]
 [4.3 5.1 6.2]]
float64
[[ True  True  True]
 [ True  True  True]]
bool


In [90]:
# fungsi copy
arr = np.array([1, 2, 3]) # arrar 1 dimensi
arr1 = arr.copy() # salin array

print(arr)
print(arr1)

arr[0] = 10 # ubah nilai array

print(arr1)
print(arr) # array asli tidak berubah

[1 2 3]
[1 2 3]
[1 2 3]
[10  2  3]


In [ ]:
# fungsi view
arr = np.array([1, 2, 3]) # arrar 1 dimensi
arr1 = arr.view() # salin array

print(arr)
print(arr1)

arr[0] = 10 # ubah nilai array

print(arr1)
print(arr) # array asli tidak berubah

[1 2 3]
[1 2 3]
[10  2  3]
[10  2  3]


In [99]:
# fungsi base
x = np.array(['a', 'b']) 
y = x.view() # salin array

print(x.base)
print(y.base)

None
['a' 'b']
